FROM python:3
WORKDIR /usr/src/app
COPY indian-cities/indian-cities-test.py ./
RUN pip install pytest
RUN pip install requests
COPY . .
CMD [ "pipenv", "install"]
CMD [ "pytest", "indian-cities/indian-cities-test.py"]
